name: Tests

on: [pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_USER: test
      POSTGRES_DB: test
      POSTGRES_PASSWORD: ${{ secrets.TEST_DATABASE_PASSWORD }}
      DATABASE_URL: postgresql://test:${{ secrets.TEST_DATABASE_PASSWORD }}@localhost:5432/test?schema=test

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: DB container
        run: yarn start:db:ci && yarn db:deploy
      - name: Install dependencies
        run: yarn --frozen-lockfile
      - name: Lint code
        run: yarn lint .
      - name: Test
        run: yarn test:cov
      - name: Build
        run: yarn build
      - name: DB container down
        run: yarn stop:db:ci
      - uses: codecov/codecov-action@v1
